language: java
addons:
  sonarcloud:
    organization: "davidgfolch-github"
    token:
      secure: "iVQWA574puIf1ueOUcBzqFB5m6gzYDyhYAnj2hBKv3iJuTYXXQWJ/K5BfdMf6Rb0vdx4a0TzQw6pVM9j+rAZmCSibRRBBOx4+5r9DQ14IDdR7xRtx6OUmTLhGEDJFyB9GIM+MyI1xzoCisMk+t8H/Q8ZDyQqgaf+oOUCFV8yRAJ/7e48+auD7xPMdB6r6XEe0uccFAlOXqm+9YXAl6GtgL5EykifYetKoYMbwtqhGKJjlmW84tzE+sSAtEvDh7ywSlzJew/uaSzm9gNSwWgnskkB+8kiaXYDQxSuZoLhVsVE+Mo5rTHq5dDq9jzyFH32LVpyo9yMNM0tZ7Hvb8OocCwsfMZIW2rZMpa02yxVa90P2aM01sTG36dV8W3oBrxpZl0uV1Y5AbFl2qTlwt/ZS9Mh4dqjA5XI1bGCUsld1Y2ROehPDTOfv7P6rrZkOrYKAyAFVta6ECKBQKOihonGgNJp7ec/o+VLGZWpbZKPOF36z+QZnQso8b4SGm+bF0h30Mne6Q5Ozzvgi5II45kEK14lVyT3MwlXcLjyBdHL+69JXKoWK04W77kvmt1q0qHFPnRMVaA0ryXL4H+FolJk5Tj1Bk5zbh41KAsMdDiybpgxFiMbvcACA0Vm4gWfKivPzHITOLf2Xt2TwlZzcW1iq7r/8O4oA3W9Q/pT4g/1JWY="

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build jacocoTestReport sonarqube
#  - sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
